title: Halldór Úlfarsson Research Profile
description: Research documentation and projects by Halldor Ulfarsson
theme: just-the-docs
baseurl: /Research
url: https://HalldorUlfarsson.github.io
color_scheme: dark
search_enabled: true
heading_anchors: true
footer_content: "Copyright © 2026 Halldor Ulfarsson. No rights reserved."

aux_links: 
  "halldorphone":
    - "https://www.halldorophone.info/"

nav_enabled: true

collections:
  docs:
    output: true
    permalink: /:collection/:path/

just-the-docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: False
