title: Halldór Úlfarsson Research Profile
description: Research documentation and projects by Halldor Ulfarsson
theme: just-the-docs
baseurl: /Research
url: https://HalldorUlfarsson.github.io
color_scheme: dark
search_enabled: true
heading_anchors: true
footer_content: "Copyright © 2026 Halldor Ulfarsson. All rights reserved."
aux_links:
  - title: "GitHub"
    url: "https://github.com/HalldorUlfarsson"

collections:
  docs:
    output: true
    permalink: /:collection/:path/

just-the-docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: False
