title: Halldor Ulfarsson Research
description: Research documentation and projects by Halldor Ulfarsson
theme: just-the-docs
baseurl: /Research
url: https://HalldorUlfarsson.github.io
color_scheme: dark
search_enabled: true
heading_anchors: true
nav_folder_structure: true
footer_content: "Copyright &copy; 2026 Halldor Ulfarsson. All rights reserved."
aux_links: 
  GitHub: https://github.com/HalldorUlfarsson